### Import the numpy package under the name `np`.

In [1]:
import numpy as np

### Print the numpy version and the configuration.

In [3]:
np.__version__, np.show_config()

openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None

('1.22.3', None)

### Create a null vector of size 10.

In [5]:
print("Null vector of size 10 is : ")
np.zeros(shape=10)

Null vector of size 10 is : 


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### How to find the memory size of any array.

In [19]:
array =  np.zeros(shape=10)
array
print("Total elements of the array is : ", array.size)
print("Size of each element of array is : ", array.itemsize, "bytes")
print("Memory size of an array is : ", array.size * array.itemsize, "bytes")

Total elements of the array is :  10
Size of each element of array is :  8 bytes
Memory size of an array is :  80 bytes


### Create a null vector of size 10 but the fifth value which is `1`.

In [23]:
array = np.zeros(shape=10, dtype=int)
print("Original Array : ", array)
array[4] = 1
print("After updation, array is : ", array)

Original Array :  [0 0 0 0 0 0 0 0 0 0]
After updation, array is :  [0 0 0 0 1 0 0 0 0 0]


### Create a vector with values ranging from 10 to 49.

In [24]:
vector = np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### Reverse a vector (first element becomes last).

In [26]:
# First method
vector = np.arange(10,20)
print("Original Vector : ", vector)
reversed_vector = vector[::-1]
print("Reversed Vector : ", reversed_vector)

Original Vector :  [10 11 12 13 14 15 16 17 18 19]
Reversed Vector :  [19 18 17 16 15 14 13 12 11 10]


In [53]:
# second method
vector = np.arange(2,12)
print("Original Vector : ", vector)
reversed_vector = sorted(vector, reverse=True)
print("Reversed Vector : ", reversed_vector)

Original Vector :  [ 2  3  4  5  6  7  8  9 10 11]
Reversed Vector :  [11, 10, 9, 8, 7, 6, 5, 4, 3, 2]


In [54]:
# Third method
vector = np.arange(20,28)
print("Original Vector : ", vector)
reversed_vector = []
for i in range(len(vector)-1, -1, -1):
    reversed_vector.append(vector[i])
print("Reversed Vector : ", reversed_vector)

Original Vector :  [20 21 22 23 24 25 26 27]
Reversed Vector :  [27, 26, 25, 24, 23, 22, 21, 20]


### Create a `3x3` matrix with values ranging from `0 to 8`.

In [57]:
matrix = np.arange(0,9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Find indices of non-zero elements from `[1,2,0,0,4,0]`.

In [65]:
array = [1,2,0,0,4,0]
array = np.nonzero([array])
print("Total non-zeros elements are : ",len(array[0]))
print("Indices of non-zeros elements are : " , array[1])
print(array)

Total non-zeros elements are :  3
Indices of non-zeros elements are :  [0 1 4]
(array([0, 0, 0]), array([0, 1, 4]))


### Create a 3x3 identity matrix of type integer. `(Hint np.eye())`

In [69]:
matrix = np.eye(3, dtype = int)
matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### Create a 3x3x3 array with random values

In [89]:
# First Method
array = np.random.randint(1,100, 27).reshape(3,3,3)
print("3x3x3 array with random values : " , array, sep="\n")

3x3x3 array with random values : 
[[[49 98 97]
  [58 88 99]
  [81 84 52]]

 [[53 35  4]
  [49 98 53]
  [65 67 61]]

 [[10 84 13]
  [51 32 99]
  [12 25 32]]]


In [93]:
# Second Method
array = np.random.randint(1,100, (3,3,3))
print("3x3x3 array with random values : " , array, sep="\n")

3x3x3 array with random values : 
[[[97 58 96]
  [16 89  1]
  [ 7 78 26]]

 [[27 60 73]
  [78 72 41]
  [58 22 65]]

 [[82 82 60]
  [91 37 30]
  [31 95 83]]]


In [95]:
# Third Method
array = np.random.random((3,3,3))
print("3x3x3 array with random values : " , array, sep="\n")

3x3x3 array with random values : 
[[[0.69292722 0.68902246 0.04786369]
  [0.80568531 0.14118223 0.79656065]
  [0.24070537 0.46495718 0.5992354 ]]

 [[0.92245723 0.81750677 0.79519082]
  [0.1845357  0.33108126 0.97306186]
  [0.53395456 0.11425567 0.89177813]]

 [[0.59385643 0.71290632 0.68688431]
  [0.1043174  0.80897724 0.2160545 ]
  [0.689038   0.93475177 0.71101708]]]


### Create a 10x10 array with random values and find the minimum and maximum values.

In [104]:
# First Method
array = np.random.randint(10,100, (10,10))
print("10x10 array with random values : ",array, sep="\n")
print("Minimum value in 10x10 is : ", array.min())
print("Maximum value in 10x10 is : ", array.max())

10x10 array with random values : 
[[71 63 63 96 73 75 82 91 53 60]
 [37 98 79 52 23 75 26 13 83 21]
 [29 13 63 87 12 20 41 25 59 21]
 [65 87 85 33 46 78 12 61 64 99]
 [64 95 79 81 96 69 84 36 18 46]
 [27 94 59 63 63 84 62 20 28 85]
 [90 74 52 23 11 90 73 82 18 32]
 [16 10 39 70 94 82 40 49 80 22]
 [13 53 25 81 70 58 64 87 92 46]
 [22 39 11 22 66 71 44 91 90 25]]
Minimum value in 10x10 is :  10
Maximum value in 10x10 is :  99


In [108]:
array = np.random.random((10,10))
print("10x10 array with random values : ",array, sep="\n")
print("Minimum value in 10x10 is : ", array.min())
print("Maximum value in 10x10 is : ", array.max())

10x10 array with random values : 
[[0.81686429 0.0771806  0.31932817 0.14231927 0.91868018 0.26019433
  0.04753259 0.6664626  0.58548678 0.6792984 ]
 [0.84508414 0.84972386 0.01600216 0.49863144 0.98565401 0.33655439
  0.07387186 0.15524781 0.73703025 0.09632862]
 [0.07172783 0.87946976 0.38722663 0.91460394 0.40062507 0.53798833
  0.33595374 0.77916906 0.9562804  0.2386366 ]
 [0.19036763 0.69004783 0.23319203 0.63590758 0.62795477 0.02804543
  0.88026805 0.45150703 0.02331299 0.90044219]
 [0.49750986 0.32719965 0.24305229 0.29477505 0.12804083 0.82310887
  0.28241807 0.86513913 0.16372487 0.39901724]
 [0.4750039  0.14476457 0.27456    0.52739576 0.54817933 0.07542734
  0.39396306 0.73564815 0.37696986 0.7203146 ]
 [0.58128364 0.99988192 0.98445367 0.82812611 0.25322176 0.54117692
  0.92877352 0.98069159 0.0025231  0.39066292]
 [0.40952955 0.60936616 0.67210068 0.16313701 0.20107917 0.13185477
  0.41157902 0.4605959  0.30127889 0.93735508]
 [0.86372495 0.33724011 0.59164013 0.17248571 

### Create a random vector of size 30 and find the `mean` value.

In [112]:
# First Method
vector = np.random.randint(1,100, 30)
print("vector : ", vector , sep="\n")
print("Mean of the vector is : ", vector.mean())

vector : 
[63 19 70 37 72 95 34 76 25 70  1 85 30 62 31 62 27 28 27 63 12 35 40 45
 77 34 16 82 80 11]
Mean of the vector is :  46.96666666666667


In [115]:
# Second Method
vector = np.random.random(size=30)
print("vector : ", vector , sep="\n")
print("Mean of the vector is : ", vector.mean())

vector : 
[0.40646101 0.63508348 0.86852128 0.35128457 0.89982337 0.7210841
 0.23058575 0.66442415 0.97797253 0.32020707 0.58795864 0.10433148
 0.86495337 0.46457668 0.82929115 0.81885063 0.54202214 0.77887757
 0.10878504 0.02729844 0.67666325 0.9977666  0.64325026 0.68571911
 0.14396261 0.24737626 0.03337356 0.59076535 0.63416392 0.84389635]
Mean of the vector is :  0.5566443237261397


### Create a 2d array with `1` on the border and `0` inside.

In [123]:
array2D = np.ones((10,10), dtype=int)
array2D

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [125]:
array2D[1:-1,1:-1]=0
print("2d array with 1 on the border and 0 inside : ", array2D, sep="\n")

2d array with 1 on the border and 0 inside : 
[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


### How to add a border (filled with 0's) around an existing array.

In [146]:
# First Method
array = np.ones((5,5), dtype=int)
array = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print(array)

[[0 0 0 0 0 0 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0]]


In [153]:
# Second method
array = np.random.randint(1,10,(5,5))
array = np.pad(array, pad_width=1, mode='constant', constant_values=0)
array

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 6, 8, 2, 7, 1, 0],
       [0, 4, 6, 7, 7, 3, 0],
       [0, 7, 4, 1, 3, 9, 0],
       [0, 3, 2, 5, 8, 7, 0],
       [0, 1, 6, 9, 1, 7, 0],
       [0, 0, 0, 0, 0, 0, 0]])

### What is the result of the following expression?
- 0 * np.nan
- np.nan == np.nan
- np.inf > np.nan
- np.nan - np.nan
- np.nan in set([np.nan])
- 0.3 == 3 * 0.1

In [157]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


### Create a 5x5 matrix with values `1,2,3,4` just below the diagonal.

### numpy.diag() function
- This function is used to extract diagonal or construct diagonal array.

#### Syntax:
```
numpy.diag(v, k=0)
```

Parameters:
- `v` : If v is a 2-D array, return a copy of its k-th diagonal. If v is a 1-D array, return a 2-D array with v on the k-th diagonal.
- `k` : Diagonal in question. The default is 0. Use k>0 for diagonals above the main diagonal, and k<0 for diagonals below the main diagonal.

In [181]:
matrix2 =np.random.randint(12,16,(3,3))
matrix2

array([[13, 15, 15],
       [13, 13, 12],
       [13, 12, 12]])

In [182]:
np.diag(matrix2, k=1)

array([15, 12])

In [164]:
matrix = np.diagonal(matrxi)
matrix

array([18,  2,  2, 14,  5])

In [163]:
matrxi = np.random.randint(1,20,(5,5))
matrxi

array([[18,  3, 16,  4,  9],
       [ 1,  2,  6,  2,  3],
       [13,  5,  2, 18,  8],
       [ 7,  3,  6, 14,  1],
       [17,  6,  8, 19,  5]])

In [171]:
np.diag([1,2,3,4], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [172]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [174]:
np.arange(4)

array([0, 1, 2, 3])