### Import the numpy package under the name `np`.

In [1]:
import numpy as np

### Print the numpy version and the configuration.

In [3]:
np.__version__, np.show_config()

openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None

('1.22.3', None)

### Create a null vector of size 10.

In [5]:
print("Null vector of size 10 is : ")
np.zeros(shape=10)

Null vector of size 10 is : 


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### How to find the memory size of any array.

In [19]:
array =  np.zeros(shape=10)
array
print("Total elements of the array is : ", array.size)
print("Size of each element of array is : ", array.itemsize, "bytes")
print("Memory size of an array is : ", array.size * array.itemsize, "bytes")

Total elements of the array is :  10
Size of each element of array is :  8 bytes
Memory size of an array is :  80 bytes


### Create a null vector of size 10 but the fifth value which is `1`.

In [23]:
array = np.zeros(shape=10, dtype=int)
print("Original Array : ", array)
array[4] = 1
print("After updation, array is : ", array)

Original Array :  [0 0 0 0 0 0 0 0 0 0]
After updation, array is :  [0 0 0 0 1 0 0 0 0 0]


### Create a vector with values ranging from 10 to 49.

In [24]:
vector = np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### Reverse a vector (first element becomes last).

In [26]:
# First method
vector = np.arange(10,20)
print("Original Vector : ", vector)
reversed_vector = vector[::-1]
print("Reversed Vector : ", reversed_vector)

Original Vector :  [10 11 12 13 14 15 16 17 18 19]
Reversed Vector :  [19 18 17 16 15 14 13 12 11 10]


In [53]:
# second method
vector = np.arange(2,12)
print("Original Vector : ", vector)
reversed_vector = sorted(vector, reverse=True)
print("Reversed Vector : ", reversed_vector)

Original Vector :  [ 2  3  4  5  6  7  8  9 10 11]
Reversed Vector :  [11, 10, 9, 8, 7, 6, 5, 4, 3, 2]


In [54]:
# Third method
vector = np.arange(20,28)
print("Original Vector : ", vector)
reversed_vector = []
for i in range(len(vector)-1, -1, -1):
    reversed_vector.append(vector[i])
print("Reversed Vector : ", reversed_vector)

Original Vector :  [20 21 22 23 24 25 26 27]
Reversed Vector :  [27, 26, 25, 24, 23, 22, 21, 20]


### Create a `3x3` matrix with values ranging from `0 to 8`.

In [57]:
matrix = np.arange(0,9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Find indices of non-zero elements from `[1,2,0,0,4,0]`.

In [65]:
array = [1,2,0,0,4,0]
array = np.nonzero([array])
print("Total non-zeros elements are : ",len(array[0]))
print("Indices of non-zeros elements are : " , array[1])
print(array)

Total non-zeros elements are :  3
Indices of non-zeros elements are :  [0 1 4]
(array([0, 0, 0]), array([0, 1, 4]))


### Create a 3x3 identity matrix of type integer. `(Hint np.eye())`

In [69]:
matrix = np.eye(3, dtype = int)
matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### Create a 3x3x3 array with random values

In [89]:
# First Method
array = np.random.randint(1,100, 27).reshape(3,3,3)
print("3x3x3 array with random values : " , array, sep="\n")

3x3x3 array with random values : 
[[[49 98 97]
  [58 88 99]
  [81 84 52]]

 [[53 35  4]
  [49 98 53]
  [65 67 61]]

 [[10 84 13]
  [51 32 99]
  [12 25 32]]]


In [93]:
# Second Method
array = np.random.randint(1,100, (3,3,3))
print("3x3x3 array with random values : " , array, sep="\n")

3x3x3 array with random values : 
[[[97 58 96]
  [16 89  1]
  [ 7 78 26]]

 [[27 60 73]
  [78 72 41]
  [58 22 65]]

 [[82 82 60]
  [91 37 30]
  [31 95 83]]]


In [95]:
# Third Method
array = np.random.random((3,3,3))
print("3x3x3 array with random values : " , array, sep="\n")

3x3x3 array with random values : 
[[[0.69292722 0.68902246 0.04786369]
  [0.80568531 0.14118223 0.79656065]
  [0.24070537 0.46495718 0.5992354 ]]

 [[0.92245723 0.81750677 0.79519082]
  [0.1845357  0.33108126 0.97306186]
  [0.53395456 0.11425567 0.89177813]]

 [[0.59385643 0.71290632 0.68688431]
  [0.1043174  0.80897724 0.2160545 ]
  [0.689038   0.93475177 0.71101708]]]


### Create a 10x10 array with random values and find the minimum and maximum values.

In [104]:
# First Method
array = np.random.randint(10,100, (10,10))
print("10x10 array with random values : ",array, sep="\n")
print("Minimum value in 10x10 is : ", array.min())
print("Maximum value in 10x10 is : ", array.max())

10x10 array with random values : 
[[71 63 63 96 73 75 82 91 53 60]
 [37 98 79 52 23 75 26 13 83 21]
 [29 13 63 87 12 20 41 25 59 21]
 [65 87 85 33 46 78 12 61 64 99]
 [64 95 79 81 96 69 84 36 18 46]
 [27 94 59 63 63 84 62 20 28 85]
 [90 74 52 23 11 90 73 82 18 32]
 [16 10 39 70 94 82 40 49 80 22]
 [13 53 25 81 70 58 64 87 92 46]
 [22 39 11 22 66 71 44 91 90 25]]
Minimum value in 10x10 is :  10
Maximum value in 10x10 is :  99


In [108]:
array = np.random.random((10,10))
print("10x10 array with random values : ",array, sep="\n")
print("Minimum value in 10x10 is : ", array.min())
print("Maximum value in 10x10 is : ", array.max())

10x10 array with random values : 
[[0.81686429 0.0771806  0.31932817 0.14231927 0.91868018 0.26019433
  0.04753259 0.6664626  0.58548678 0.6792984 ]
 [0.84508414 0.84972386 0.01600216 0.49863144 0.98565401 0.33655439
  0.07387186 0.15524781 0.73703025 0.09632862]
 [0.07172783 0.87946976 0.38722663 0.91460394 0.40062507 0.53798833
  0.33595374 0.77916906 0.9562804  0.2386366 ]
 [0.19036763 0.69004783 0.23319203 0.63590758 0.62795477 0.02804543
  0.88026805 0.45150703 0.02331299 0.90044219]
 [0.49750986 0.32719965 0.24305229 0.29477505 0.12804083 0.82310887
  0.28241807 0.86513913 0.16372487 0.39901724]
 [0.4750039  0.14476457 0.27456    0.52739576 0.54817933 0.07542734
  0.39396306 0.73564815 0.37696986 0.7203146 ]
 [0.58128364 0.99988192 0.98445367 0.82812611 0.25322176 0.54117692
  0.92877352 0.98069159 0.0025231  0.39066292]
 [0.40952955 0.60936616 0.67210068 0.16313701 0.20107917 0.13185477
  0.41157902 0.4605959  0.30127889 0.93735508]
 [0.86372495 0.33724011 0.59164013 0.17248571 

### Create a random vector of size 30 and find the `mean` value.

In [112]:
# First Method
vector = np.random.randint(1,100, 30)
print("vector : ", vector , sep="\n")
print("Mean of the vector is : ", vector.mean())

vector : 
[63 19 70 37 72 95 34 76 25 70  1 85 30 62 31 62 27 28 27 63 12 35 40 45
 77 34 16 82 80 11]
Mean of the vector is :  46.96666666666667


In [115]:
# Second Method
vector = np.random.random(size=30)
print("vector : ", vector , sep="\n")
print("Mean of the vector is : ", vector.mean())

vector : 
[0.40646101 0.63508348 0.86852128 0.35128457 0.89982337 0.7210841
 0.23058575 0.66442415 0.97797253 0.32020707 0.58795864 0.10433148
 0.86495337 0.46457668 0.82929115 0.81885063 0.54202214 0.77887757
 0.10878504 0.02729844 0.67666325 0.9977666  0.64325026 0.68571911
 0.14396261 0.24737626 0.03337356 0.59076535 0.63416392 0.84389635]
Mean of the vector is :  0.5566443237261397


### Create a 2d array with `1` on the border and `0` inside.

In [123]:
array2D = np.ones((10,10), dtype=int)
array2D

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [125]:
array2D[1:-1,1:-1]=0
print("2d array with 1 on the border and 0 inside : ", array2D, sep="\n")

2d array with 1 on the border and 0 inside : 
[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


### How to add a border (filled with 0's) around an existing array.

In [146]:
# First Method
array = np.ones((5,5), dtype=int)
array = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print(array)

[[0 0 0 0 0 0 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0]]


In [153]:
# Second method
array = np.random.randint(1,10,(5,5))
array = np.pad(array, pad_width=1, mode='constant', constant_values=0)
array

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 6, 8, 2, 7, 1, 0],
       [0, 4, 6, 7, 7, 3, 0],
       [0, 7, 4, 1, 3, 9, 0],
       [0, 3, 2, 5, 8, 7, 0],
       [0, 1, 6, 9, 1, 7, 0],
       [0, 0, 0, 0, 0, 0, 0]])

### What is the result of the following expression?
- 0 * np.nan
- np.nan == np.nan
- np.inf > np.nan
- np.nan - np.nan
- np.nan in set([np.nan])
- 0.3 == 3 * 0.1

In [157]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


### Create a 5x5 matrix with values `1,2,3,4` just below the diagonal.

In [188]:
# First method
matrix = np.diag([1,2,3,4], k=-1)
print("5x5 matrix with values 1,2,3,4 just below the diagonal : ", matrix,sep="\n")

5x5 matrix with values 1,2,3,4 just below the diagonal : 
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [191]:
# Second method
a = 1 + np.arange(4)
matrix = np.diag(a, k=-1)
print("5x5 matrix with values 1,2,3,4 just below the diagonal : ", matrix,sep="\n")

5x5 matrix with values 1,2,3,4 just below the diagonal : 
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### numpy.diag() function
- This function is used to extract diagonal or construct diagonal array.

#### Syntax:
```
numpy.diag(v, k=0)
```

Parameters:
- `v` : If v is a 2-D array, return a copy of its k-th diagonal. If v is a 1-D array, return a 2-D array with v on the k-th diagonal.
- `k` : Diagonal in question. The default is 0. Use k>0 for diagonals above the main diagonal, and k<0 for diagonals below the main diagonal.

![](images/numpy-diag-function-image-a.png)

### Examples

In [185]:
import numpy as np
a = np.arange(12).reshape((4,3))
print("Original Array : ", a, sep="\n")
print("Diagonal of given array is : ", np.diag(a))

Original Array : 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Diagonal of given array is :  [0 4 8]


#### Pictorial Presentation
<img src="images/numpy-diag-function-image-1.png" height=200px width=200px >

### Create a `8x8` matrix and fill it with a checkerboard pattern.
<img src="images/1200px-Checkerboard_Pattern_8x6.svg.png" height=400px width=400px>

In [203]:
matrix = np.zeros((8,8),dtype=int)

matrix[1::2, ::2] = 1
#     x[1::2, ::2] = 1 : Slice from 1st index row till 1+2+2… and 
#fill all columns with 1 starting from 0th to 0+2+2… and so on.


matrix[::2,1::2] = 1
# x[::2, 1::2] = 1 : Slice from 0th row till 0+2+2… and fill all columns with 1 starting from 1 to 1+2+2+…..
print("Checkerboard pattern of 8x8 matrix is : ", matrix, sep="\n")

# Note: we can print che checkerboard pattern of any size of matrix

Checkerboard pattern of 8x8 matrix is : 
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Find similar elements between two matrix of different shapes.

In [331]:
# First Method
# First matrix of (3,3)
matrix1 = np.random.randint(1,20, (3,3))

# Second matrix of (4,3)
matrix2 = np.random.randint(5,20,(4,3))
print("First Matrix : ", matrix1, sep="\n")
print("\n\n")
print("Second Matrix : ", matrix2, sep="\n")
print("\n")
def check_similar_elements(mat1, mat2):
    return set([items for items in mat1 if items in mat2])

items = list(check_similar_elements(matrix1.flatten(), matrix2.flatten()))
print("List of similar items of two matrix are : ", items, sep="\n")



First Matrix : 
[[16 18  4]
 [10  6  7]
 [10 10  9]]



Second Matrix : 
[[11 17 10]
 [16  9 10]
 [12 14 11]
 [15 14 18]]


List of similar items of two matrix are : 
[16, 9, 18, 10]


In [332]:
# Second method
items = np.intersect1d(matrix1, matrix2)
print("List of similar items of two matrix are : ", items, sep="\n")

List of similar items of two matrix are : 
[ 9 10 16 18]


### Create a checkerboard 8x8 matrix using the `tile` function.

In [247]:
matrix = np.array([[0,1],[1,0]])
print("Checkerboard of 8x8 using title function : ", np.tile(matrix, (4,4)), sep="\n")

Checkerboard of 8x8 using title function : 
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Normalize a 5x5 random matrix using numpy.
<img src="images/1616512439644.jpeg" height=500px width=500px>

In [267]:
# First method
matrix = np.random.randint(1,20,(5,5))
print("Before Normalization matrix is : ", matrix, sep="\n")

# Normalization Formula
Xmax , Xmin = matrix.max(), matrix.min()
Xnormalized = (matrix-Xmin)/(Xmax-Xmin)

print("\n\n")

print("After Normalization matrix is : ", Xnormalized, sep="\n")

Before Normalization matrix is : 
[[16 12 17  3 15]
 [ 3  2 12  7  2]
 [10 17 15  5 14]
 [10 10  8 14  6]
 [ 5 13  3  5 18]]



After Normalization matrix is : 
[[0.875  0.625  0.9375 0.0625 0.8125]
 [0.0625 0.     0.625  0.3125 0.    ]
 [0.5    0.9375 0.8125 0.1875 0.75  ]
 [0.5    0.5    0.375  0.75   0.25  ]
 [0.1875 0.6875 0.0625 0.1875 1.    ]]


In [269]:
# Second method
matrix = np.random.random((5,5))
print("Before Normalization matrix is : ", matrix, sep="\n")
Normalized = (matrix-np.mean(matrix))/np.std(matrix)
print("\n\n")
print("After Normalization matrix is : ", Normalized, sep="\n")

Before Normalization matrix is : 
[[0.3757811  0.04411975 0.05685107 0.97622709 0.76229347]
 [0.16058966 0.1863095  0.20297079 0.4095602  0.81819878]
 [0.41258205 0.66500263 0.4945396  0.73404388 0.05487725]
 [0.4739625  0.90352041 0.03278523 0.36256798 0.74032356]
 [0.88103226 0.27657728 0.64787112 0.2778744  0.7779088 ]]



After Normalization matrix is : 
[[-0.31523606 -1.43518734 -1.39219634  1.71234498  0.98993573]
 [-1.04189271 -0.95504219 -0.89878046 -0.20117105  1.1787163 ]
 [-0.19096691  0.66140483  0.08578667  0.89454272 -1.39886151]
 [ 0.0163021   1.46682969 -1.47346166 -0.35985399  0.91574789]
 [ 1.39089187 -0.65022668  0.60355526 -0.64584659  1.04266545]]


In [277]:
# Third Method
matrix = np.random.randint(100,2000,(5,5))
print("Before Normalization matrix is : ", matrix, sep="\n")
normalized = (matrix - np.mean(matrix))/np.std(matrix)
print("\n\n")
print("After Normalization matrix is : ", normalized, sep="\n")

Before Normalization matrix is : 
[[ 382  585  552 1962  654]
 [ 397  655 1186  152  511]
 [1610 1462 1877 1227  894]
 [1099 1765 1847  129  173]
 [ 595  110  792  452  616]]



After Normalization matrix is : 
[[-0.83458655 -0.48552386 -0.54226804  1.8822561  -0.36687693]
 [-0.80879374 -0.36515741  0.54790807 -1.23007631 -0.61276839]
 [ 1.27698483  1.02249577  1.73609685  0.61840841  0.04580803]
 [ 0.39830977  1.54351053  1.68451123 -1.26962528 -1.19396637]
 [-0.46832865 -1.30229617 -0.12958308 -0.7142201  -0.43221872]]


### Create a custom dtype that describes a color as four `unsigned bytes (RGBA)`.

In [285]:
colors =np.dtype([('r', np.ubyte),
                 ('g', np.ubyte),
                  ('b', np.ubyte),
                 ('a', np.ubyte)])
print(colors)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


### Multiply a 5x3 matrix by a 3x2 matrix `(real matrix product)`.

In [293]:
matrix1 = np.ones((5,3), dtype=np.int8)
print("First Matrix is : ", matrix1, sep="\n")
matrix2 = np.ones((3,2), dtype=np.int8)
print("Second Matrix is : ", matrix2, sep="\n")
product = np.dot(matrix1, matrix2)
print("Product of both matrices are : ", product, sep="\n")

First Matrix is : 
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
Second Matrix is : 
[[1 1]
 [1 1]
 [1 1]]
Product of both matrices are : 
[[3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]]


In [297]:
# Second method
matrix1 = np.ones((5,3), dtype=np.int8)
print("First Matrix is : ", matrix1, sep="\n")
matrix2 = np.ones((3,2), dtype=np.int8)
print("Second Matrix is : ", matrix2, sep="\n")
product = matrix1 @ matrix2
print("Product of both matrices are : ", product, sep="\n")

First Matrix is : 
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
Second Matrix is : 
[[1 1]
 [1 1]
 [1 1]]
Product of both matrices are : 
[[3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]]


### Given a 1D array, `negate` all elements which are between 3 and 8, in place.
##### Input : 1,2,3,4,5,6,7,8,9,10,....
##### Output : 1,2,3,-4,-5,-6,-7,8,9,10,...

In [310]:
array = np.arange(11)
print("Original Array : ", array)
array[(array>3) & (array<8)] = array[(array>3) & (array<8)] * -1
print("After negation array is : ", array)

Original Array :  [ 0  1  2  3  4  5  6  7  8  9 10]
After negation array is :  [ 0  1  2  3 -4 -5 -6 -7  8  9 10]


### Consider an integer vector Z, which of these expressions are legal? 

In [333]:
Z = np.array([2,3,4])
# Z**Z    -> Legal
# 2 << Z >> 2    -> Legal
# Z <- Z    -> Legal
# 1j*Z      -> Legal
# Z/1/1     -> Legal
# Z<Z>Z     -> illegal

In [360]:
a = np.random.uniform(-10,10,10)
a

array([ 0.49180451,  5.86908851, -4.59592205, -3.91916009,  4.53561511,
        4.27698951, -4.04740018,  6.5090785 , -1.36064052, -5.3508564 ])

In [350]:
b = np.abs(a)
b

array([8.94368824, 8.27683616, 4.15147233, 7.57505935, 9.0957827 ,
       1.33284117, 5.79328991, 1.14798067, 4.95647526, 0.93472442])

In [355]:
c =np.ceil(b)
c

array([ 9.,  9.,  5.,  8., 10.,  2.,  6.,  2.,  5.,  1.])

In [356]:
np.copysign(c,a)

array([ 9.,  9.,  5.,  8., 10.,  2.,  6.,  2.,  5.,  1.])

### How to round away from zero a float array ?

In [375]:
# First Method
array = np.random.uniform(-10,10,10)
print("Array is : ", array, sep="\n")
a = np.ceil(np.abs(array))
print("New rounded array is : ",np.copysign(a,array))

Array is : 
[ 5.05347514  8.75053478 -1.69180044  0.73318578  9.66359751  5.67551271
  1.13550441 -8.29336928  8.35469895  8.71679698]
New rounded array is :  [ 6.  9. -2.  1. 10.  6.  2. -9.  9.  9.]


In [376]:
# Second Method
# More readable but less efficient
print(np.where(array>0, np.ceil(array), np.floor(array)))

[ 6.  9. -2.  1. 10.  6.  2. -9.  9.  9.]
